mychat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('mychatapp.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mychatapp/urls.py
from django.urls import path
from . import views

app_name = 'mychat'

urlpatterns = [
    path('', views.index, name='index'),
    path('register', views.register, name='register'),
    path('login', views.login_page, name='login'),
    path('logout', views.log_out, name='logout'),
    path('update_profile', views.update_profile, name='update_profile'),
    path('add_friend', views.add_friend, name='add_friend'),
    path('remove_friend/<str:pk>', views.remove_friend, name='remove_friend'),
    path('send_friend_request', views.send_friend_request, name='send_friend_request'),
    path('friend_request_notification', views.friend_request_notification, name='friend_request_notification'),
    path('accept_friend_request', views.accept_friend_request, name='accept_friend_request'),
    path('friend/<str:pk>', views.chatroom, name='chatroom'),
    path('sent_msg/<str:pk>', views.sentMessages, name='sent_msg'),
    path('rec_msg/<str:pk>', views.receivedMessages, name='rec_msg'),
    path('notification', views.chatNotification, name='notification'),
    path('request_notification', views.requestNotification, name='request_notification'),

    # Responsive paths
    path('my_profile', views.my_profile, name = 'my_profile')
]

mychatapp/models.py
import profile

from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    objects = None
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, blank=True, null=True)
    first_name = models.CharField(max_length=50, blank=True, null=True)
    last_name = models.CharField(max_length=50, blank=True, null=True)
    pic = models.ImageField(upload_to='img', blank=True, null=True)
    friends = models.ManyToManyField(User, related_name='my_friends', blank=True)

        
    def __str__(self):
        return self.name

class FriendRequest(models.Model):
    objects = None
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_request')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='received_request')
    seen = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.sender.username} sent {self.receiver.username} a friend request"


class ChatMessage(models.Model):
    objects = None
    body = models.TextField()
    msg_sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="msg_sender")
    msg_receiver = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="msg_receiver")
    seen = models.BooleanField(default=False)

    def __str__(self):
        return self.body

mychatapp/forms.py
from django import forms
from django.forms import ModelForm
from .models import ChatMessage, Profile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm



class ChatMessageForm(ModelForm):
    body = forms.CharField(widget=forms.Textarea(attrs={"class": "message-input", "cols": "5", "rows": "1", "placeholder": "Type message here"}))

    class Meta:
        model = ChatMessage
        fields = ["body",]


class UserForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','placeholder': 'Enter username'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter firstname'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','placeholder': 'Enter lastname'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control','placeholder': 'Enter password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control','placeholder': 'Confirm password'}))
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'password1', 'password2']


class ProfileForm(ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','placeholder': 'Enter username'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter firstname'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','placeholder': 'Enter lastname'}))
    pic = forms.ImageField(widget=forms.FileInput)
    
    class Meta:
        model = Profile
        fields = ['name', 'first_name', 'last_name', 'pic']

mychatapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout, get_user_model
from .models import Profile, ChatMessage, FriendRequest
from .forms import ChatMessageForm
from django.http import JsonResponse
from .forms import UserForm, ProfileForm
from django.contrib.auth.decorators import login_required
import json


@login_required(login_url='mychat:login')
def index(request):
    user = request.user.profile
    friends = user.friends.all()
    context = {"user": user, "friends": friends}
    return render(request, 'mychatapp/index.html', context)


def register(request):
    if request.user.is_authenticated:
        return redirect("mychat:index")
    form = UserForm()

    if request.method == 'POST':
        form = UserForm(request.POST)
        
        if form.is_valid():
            form.save()

            username = request.POST["username"]
            password = request.POST["password1"]

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect("mychat:index")
            
    context = {'form': form}
    return render(request, 'mychatapp/register.html', context)


def login_page(request):
    if request.user.is_authenticated:
        return redirect("mychat:index")
    
    error_msg = None
    if request.method == 'POST':
        username = request.POST["username"]
        password = request.POST["password"]

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect("mychat:index")
        else:
            error_msg = "Invalid Credentials"

    context = {"msg": error_msg}
    return render(request, 'mychatapp/login.html', context)


def log_out(request):
    logout(request)
    return redirect("mychat:login")


@login_required(login_url='mychat:login')
def update_profile(request):
    user = request.user
    profile = Profile.objects.get(user=user)
    form = ProfileForm(instance=profile)

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect("mychat:index")
    context = {"form": form}
    return render(request, "mychatapp/update.html", context)


@login_required(login_url='mychat:login')
def add_friend(request, *args, **kwargs):
    context = {}
    all_user = get_user_model()
    user = request.user
    profile = Profile.objects.get(user=user)
    profile_friends = profile.friends.all()

    suggestions_friends = all_user.objects.exclude(id__in = profile_friends).exclude(profile=profile)
    friend_requests = FriendRequest.objects.filter(receiver__in = suggestions_friends, sender = request.user) 
    context["s_friends"] = suggestions_friends
    context["f_requests"] = friend_requests

    if 'q' in request.GET:
        q = request.GET['q']
        data = Profile.objects.filter(name__icontains = q).exclude(id__in = profile_friends)
        data_friends = Profile.objects.filter(name__icontains = q).filter(id__in = profile_friends)
        context['data'] = data
        context['data_friends'] = data_friends

    return render(request, "mychatapp/add_friend.html", context)


def remove_friend(request, pk):
    user = get_user_model()
    n_user = user.objects.get(profile__id = pk)
    profile = Profile.objects.get(user_id = request.user.id)
    profile2 = Profile.objects.get(id = pk)
        
    if profile:
            profile.friends.remove(n_user)
            print(profile2)

    if profile2:
            profile2.friends.remove(request.user.id)
            print(request.user)

    
    return redirect("mychat:index")


def send_friend_request(request):
    data = json.loads(request.body)
    user = get_user_model()
    receiver = user.objects.get(id = data)
    friend_request = FriendRequest.objects.create(sender=request.user, receiver=receiver)

    return JsonResponse("it is giving", safe=False)


@login_required(login_url='mychat:login')
def friend_request_notification(request):
    user = request.user
    friend_requests = FriendRequest.objects.filter(receiver = user)
    friend_requests.update(seen=True)
    context = {"f_requests": friend_requests}
    return render(request, "mychatapp/friend_request.html", context)


def accept_friend_request(request):
    id = json.loads(request.body)
    user_id = id
    print(user_id)
    user = get_user_model()
    n_user = user.objects.get(id = user_id)
    profile = Profile.objects.get(user_id = request.user.id)
    profile2 = Profile.objects.get(user_id = user_id)

    msg = None

    if profile:

        if profile.friends.filter(id=user_id).exists():
            profile.friends.remove(n_user)
            FriendRequest.objects.filter(receiver = request.user, sender = user_id).delete()
            msg = "No"

        else:
            profile.friends.add(n_user)
            FriendRequest.objects.filter(receiver = request.user, sender = user_id).delete()
            msg = "Yes"

    if profile2:

        if profile2.friends.filter(id=request.user.id).exists():
            profile2.friends.remove(request.user)
            FriendRequest.objects.filter(receiver = user_id, sender = request.user).delete()

        else:
            profile2.friends.add(request.user)
            FriendRequest.objects.filter(receiver = user_id, sender = request.user).delete()

    return JsonResponse(msg, safe=False)


@login_required(login_url='mychat:login')
def chatroom(request, pk):
    friend = Profile.objects.get(id=pk)
    user = request.user.profile
    profile = Profile.objects.get(id=friend.id)
    form = ChatMessageForm()
    chats = ChatMessage.objects.all()
    rec_chats = ChatMessage.objects.filter(msg_sender=profile, msg_receiver=user)
    rec_chats.update(seen=True)

    if request.method == "POST":
        form = ChatMessageForm(request.POST)

        if form.is_valid():
            chat_message = form.save(commit=False)
            chat_message.msg_sender = user
            chat_message.msg_receiver = profile
            chat_message.save()
            return redirect("mychat:chatroom", pk=friend.profile.id)

    context = {"friend": friend, "form": form, "user": user, "profile": profile, "chats": chats, "chat_count": rec_chats.count()}
    return render(request, 'mychatapp/chat.html', context)


def sentMessages(request, pk):
    user = request.user.profile
    friend = Profile.objects.get(id=pk)
    profile = Profile.objects.get(id=friend.id)
    data = json.loads(request.body)
    new_chat = data["msg"]
    new_chat_message = ChatMessage.objects.create(body=new_chat, msg_sender=user, msg_receiver=profile, seen=False)
    print(new_chat)
    return JsonResponse(new_chat_message.body, safe=False)


def receivedMessages(request, pk):
    user = request.user.profile
    friend = Profile.objects.get(id=pk)
    profile = Profile.objects.get(id=friend.id)
    arr = []
    chats = ChatMessage.objects.filter(msg_sender=profile, msg_receiver=user)
    for chat in chats:
        arr.append(chat.body)

    return JsonResponse(arr, safe=False)


def chatNotification(request):
    user = request.user.profile
    friends = user.friends.all()
    arr = []
    for friend in friends:
        chats = ChatMessage.objects.filter(msg_sender__id=friend.profile.id, msg_receiver=user, seen=False)
        arr.append(chats.count())
    return JsonResponse(arr, safe=False)


def requestNotification(request):
    user = request.user
    arr_req = []

    requests = FriendRequest.objects.filter(receiver = user, seen = False)
    arr_req.append(requests.count())
    
    return JsonResponse(arr_req, safe=False)


# Responsive views

@login_required(login_url='mychat:login')
def my_profile(request):
    user = request.user.profile
    context = {"user": user}
    return render(request, "mychatapp/my_profile.html", context)

mychatapp/templates/mychatapp/chat.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href="{% static 'css/chat.css' %}" rel="stylesheet" />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link
    href="https://fonts.googleapis.com/css2?family=Playwrite+NZ:wght@100..400&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
    rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Noto+Serif:ital,wght@0,100..900;1,100..900&display=swap"
    rel="stylesheet">
  <title>ChatMates | Room</title>
</head>

<body>
  <div class="container">
    <!-- MENU -->
    <div class="menus">

      <a href="{% url 'mychat:index' %}">
        <button class="btn btn-home">
          <svg class="icon icon-home" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50" width="50px" height="50px">
            <path
              d="M 25 1.0507812 C 24.7825 1.0507812 24.565859 1.1197656 24.380859 1.2597656 L 1.3808594 19.210938 C 0.95085938 19.550938 0.8709375 20.179141 1.2109375 20.619141 C 1.5509375 21.049141 2.1791406 21.129062 2.6191406 20.789062 L 4 19.710938 L 4 46 C 4 46.55 4.45 47 5 47 L 19 47 L 19 29 L 31 29 L 31 47 L 45 47 C 45.55 47 46 46.55 46 46 L 46 19.710938 L 47.380859 20.789062 C 47.570859 20.929063 47.78 21 48 21 C 48.3 21 48.589063 20.869141 48.789062 20.619141 C 49.129063 20.179141 49.049141 19.550938 48.619141 19.210938 L 25.619141 1.2597656 C 25.434141 1.1197656 25.2175 1.0507812 25 1.0507812 z M 35 5 L 35 6.0507812 L 41 10.730469 L 41 5 L 35 5 z" />
          </svg>
        </button>
      </a>

      <a href="{% url 'mychat:add_friend' %}">
        <button class="btn btn-addfrnd">
          <svg class="icon icon-addfrnd" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg"
            width="50px" height="50px">
            <path
              d="M411.1 466.2c77.1 0 139.6-61.2 139.6-136.7V284c0-75.5-62.5-136.7-139.6-136.7S271.5 208.5 271.5 284v45.5c0 75.5 62.5 136.7 139.6 136.7z m228.8 123.5C568.8 561.5 491.7 546 411.1 546c-80.5 0-157.4 15.5-228.4 43.6-41.5 19.1-70.7 62-70.7 112.4v56.2c0 37.1 23.8 68.3 56.2 78.5C246.3 855 327.6 865 411.1 865c83.4 0 164.6-10 242.6-28.4 32.6-10.1 56.5-41.2 56.5-78.6v-56.2c0-50.1-28.9-93-70.3-112.1z m170-223.2v-99.7H750v99.7h-99.7v59.8H750V526h59.8v-99.7h99.7v-59.8h-99.6z" />
          </svg>
        </button>
      </a>

      <a href="{% url 'mychat:update_profile' %}">
        <button class="btn btn-settings">
          <svg class="icon icon-settings" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg">
            <path
              d="M 900.035 200.551 L 587.708 20.2292 a 151.81 151.81 0 0 0 -151.416 0 L 123.965 200.551 a 151.825 151.825 0 0 0 -75.7082 131.127 v 360.644 a 151.84 151.84 0 0 0 75.7082 131.127 l 312.327 180.322 a 151.78 151.78 0 0 0 151.416 0 l 312.327 -180.322 a 151.84 151.84 0 0 0 75.7082 -131.127 V 331.678 a 151.825 151.825 0 0 0 -75.7082 -131.127 Z M 512 673.47 a 169.98 169.98 0 1 1 169.98 -169.965 a 169.98 169.98 0 0 1 -169.98 169.965 Z" />
          </svg>
        </button>
      </a>

    </div>

    <!-- MAIN -->
    <div class="main">
      <!-- NAV -->
      <div class="nav-main">
        <div class="frnd-detail-chat">
          <a href="{% url 'mychat:index' %}">
            <svg class="icon icon-left-arrow" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg"
              xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 400.004 400.004" xml:space="preserve">
              <g>
                <path d="M382.688,182.686H59.116l77.209-77.214c6.764-6.76,6.764-17.726,0-24.485c-6.764-6.764-17.73-6.764-24.484,0L5.073,187.757
               c-6.764,6.76-6.764,17.727,0,24.485l106.768,106.775c3.381,3.383,7.812,5.072,12.242,5.072c4.43,0,8.861-1.689,12.242-5.072
               c6.764-6.76,6.764-17.726,0-24.484l-77.209-77.218h323.572c9.562,0,17.316-7.753,17.316-17.315
               C400.004,190.438,392.251,182.686,382.688,182.686z" />
              </g>
            </svg>
          </a>

          {% if friend.pic %}
          <img class="img-frnd-chat" src="{{ friend.pic.url }}" alt="user-profile" />
          {% else %}
          <img class="img-frnd-chat" src="{% static 'imgs/default-profile.jpg' %}" alt="user-profile" />
          {% endif %}
          <div>
            <h3 class="frnd-name-chat">{{ friend.name }}</h3>
          </div>
        </div>
        <a class="btn-remove-link" href="{% url 'mychat:remove_friend' friend.id %}">
          <button class="btn-edit-profile">Remove</button>
        </a>
      </div>

      <!-- CHAT -->
      <div class="chat-container">
        {% for chat in chats %}
        {% if chat.msg_sender == user and chat.msg_receiver == profile %}
        <div class="msg-container msg-container-own">
          {{chat}}
        </div>

        {% elif chat.msg_receiver == user and chat.msg_sender == profile %}
        <div class="msg-container msg-container-oth">
          {{chat}}
        </div>
        {% endif %}
        {% endfor %}
      </div>

      <!-- INPUT -->
      <div>
        <form action="" class="input-container" method="POST">
          {% csrf_token %}
          {{form.body}}
          <button type="submit" class="btn btn-send">Send</button>
        </form>
      </div>
    </div>

    <!-- DETAILS -->
    <div class="details">
      <h2 class="heading-details">{{ friend.name }}'s profile</h2>
      {% if friend.pic %}
      <img class="img-user" src="{{ friend.pic.url }}" alt="user-profile" />
      {% else %}
      <img class="img-user" src="{% static 'imgs/default-profile.jpg' %}" alt="user-profile" />
      {% endif %}
      <h3 class="user-name">{{ friend.name }}</h3>
      <a href="{% url 'mychat:remove_friend' friend.id %}">
        <button class="btn-edit-profile">Remove</button>
      </a>
    </div>

  </div>

  <!-- variable from views.py -->
  {{ chat_count|json_script:"chat_count" }}

  <script>
    function getCookie(name) {
      let cookieValue = null;
      if (document.cookie && document.cookie !== "") {
        const cookies = document.cookie.split(";");
        for (let i = 0; i < cookies.length; i++) {
          const cookie = cookies[i].trim();
          // Does this cookie string begin with the name we want?
          if (cookie.substring(0, name.length + 1) === name + "=") {
            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
            break;
          }
        }
      }
      return cookieValue;
    }
    const csrftoken = getCookie("csrftoken");


    let form = document.querySelector(".input-container");

    form.addEventListener("submit", sendChat);

    function sendChat(e) {
      e.preventDefault();

      let chatMessage = document.querySelector(".message-input").value;
      console.log(chatMessage);

      const data = { msg: chatMessage };
      let url = "{% url 'mychat:sent_msg' friend.id %}";

      fetch(url, {
        method: "POST", // or 'PUT'
        headers: {
          "Content-Type": "application/json",
          "X-CSRFToken": csrftoken,
        },
        body: JSON.stringify(data),
      })
        .then((response) => response.json())
        .then((data) => {
          console.log("Success:", data);
          let chat_body = document.querySelector(".chat-container");
          let chatMessageBox = document.createElement("div");

          chatMessageBox.classList.add("msg-container");
          chatMessageBox.classList.add("msg-container-own");

          chatMessageBox.innerText = data;
          chat_body.append(chatMessageBox);
          document.querySelector(".message-input").value = ""
          var chat_container = document.querySelector(".chat-container");
          chat_container.scrollTop = chat_container.scrollHeight - chat_container.clientHeight;
        })

        .catch((error) => {
          console.error("Error:", error);
        });
    }



    setInterval(receivedMessages, 1000)

    let counter = JSON.parse(document.getElementById('chat_count').textContent);

    function receivedMessages() {

      let url = "{% url 'mychat:rec_msg' friend.id %}";

      fetch(url)
        .then((response) => response.json())
        .then((data) => {
          console.log("Success:", data);


          if (data.length == 0) { }
          else {
            let lastMsg = data[data.length - 1]

            if (counter == data.length) { console.log("There is no new msg") }
            else {
              let chat_body = document.querySelector(".chat-container");
              let chatMessageBox = document.createElement("div");

              chatMessageBox.classList.add("msg-container");
              chatMessageBox.classList.add("msg-container-oth");

              chatMessageBox.innerText = lastMsg;
              chat_body.append(chatMessageBox);
              document.querySelector(".message-input").value = ""
              var chat_container = document.querySelector(".chat-container");
              chat_container.scrollTop = chat_container.scrollHeight - chat_container.clientHeight;
            }
          }

          counter = data.length
        })

        .catch((error) => {
          console.error("Error:", error);
        });

    }

    var chat_container = document.querySelector(".chat-container");
    chat_container.scrollTop = chat_container.scrollHeight - chat_container.clientHeight;

  </script>
</body>

</html>

mychatapp/templates/mychatapp/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ChatMates | Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
        body {

            background: #3494E6;
            /* fallback for old browsers */
            background: -webkit-linear-gradient(to right, #EC6EAD, #3494E6);
            /* Chrome 10-25, Safari 5.1-6 */
            background: linear-gradient(to right, #EC6EAD, #3494E6);
            /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
            height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;

        }

        .container {
            background-color: rgba(43, 46, 51, 0.68);
        }

        h1 {
            color: aliceblue;
        }

        input {
            width: 100%;
        }
    </style>
</head>


<body>
    <div class="container shadow p-5 m-5 rounded">

        <h1>Login</h1>
        {% if msg %}
        <p>{{msg}}</p>
        {% endif %}
        <br />

        <form action="" method="POST">
            {% csrf_token %}

            <input class="p-2 rounded" type="text" name="username" placeholder="Enter username" />
            <br />
            <br />
            <input class="p-2 rounded" type="password" name="password" placeholder="Enter password" />
            <br />
            <br />
            <button class="btn btn-secondary me-4">Submit</button>
            <a href="{% url 'mychat:register' %}" class="link-offset-2 link-underline link-underline-opacity-0">Don't
                have an account?</a>
        </form>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

mychatapp/templates/mychatapp/my_profile.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My profile</title>
    <link href="{% static 'css/my_profile.css' %}" rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
        href="https://fonts.googleapis.com/css2?family=Playwrite+NZ:wght@100..400&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Serif:ital,wght@0,100..900;1,100..900&display=swap"
        rel="stylesheet">
</head>

<body>
    <div class="container">

        <div class="details">
            <div class="nav-details">
                <a href="{% url 'mychat:index' %}">
                    <svg class="icon icon-left-arrow" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg"
                        xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 400.004 400.004" xml:space="preserve">
                        <g>
                            <path d="M382.688,182.686H59.116l77.209-77.214c6.764-6.76,6.764-17.726,0-24.485c-6.764-6.764-17.73-6.764-24.484,0L5.073,187.757
                        c-6.764,6.76-6.764,17.727,0,24.485l106.768,106.775c3.381,3.383,7.812,5.072,12.242,5.072c4.43,0,8.861-1.689,12.242-5.072
                        c6.764-6.76,6.764-17.726,0-24.484l-77.209-77.218h323.572c9.562,0,17.316-7.753,17.316-17.315
                        C400.004,190.438,392.251,182.686,382.688,182.686z" />
                        </g>
                    </svg>
                </a>
                <h2 class="heading-details">My Profile</h2>
            </div>
            {% if user.pic %}
            <img class="img-user" src="{{user.pic.url}}" alt="user-profile" />
            {% else %}
            <img class="img-user" src="{% static 'imgs/default-profile.jpg' %}" alt="user-profile" />
            {% endif %}
            <h3 class="user-name">{{user.name}}</h3>
            <h4 class="user-status">How're you doing?, I'm great🎉</h4>
            <div class="flex">
                <a href="{% url 'mychat:update_profile' %}">
                    <button class="btn-edit-profile">Edit</button>
                </a>
                <a href="{% url 'mychat:logout' %}">
                    <button class="btn-logout-profile">Logout</button>
                </a>
            </div>
        </div>
    </div>

</body>

</html>